mavenInternalUrl:https://artifacts.onesky.xyz/artifactory/internal
codeArtifactsInternalUrl:https://onesky-169922227793.d.codeartifact.us-east-1.amazonaws.com/maven/internal/
sonarqube:http://sonarqube.oneskysystems.com
dbUrl:jdbc:postgresql://localhost:5432/error_processor
dbUser:postgres
dbPassword:admin
apacheCommonsVersion:3.12.0
commonsIoVersion:2.8.0
jacksonVersion:2.13.3
lombokVersion:1.18.20
logbookVersion:2.11.0
springOauthSecurityVersion:2.5.2.RELEASE
springSecurityJwt:1.1.1.RELEASE
springCloudVersion:2020.0.3
oneskyLibsVersion:1.0.0-SNAPSHOT
oneskyCommonsVersion:1.0.7-SNAPSHOT
