spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/template_db"
    username: postgres
    password: admin
  flyway:
    clean-on-validation-error: true
    enabled: true
    schemas: template_data
